# .travis.yml --
#
# Travis CI configuration for Libexpat.   This is a forked configuration
# for:
#
#   <https://github.com/marcomaggi/libexpat>
#

#page
#### about compiler packages
#
# We select build  by build the packages to install;  it should speed up
# preparation.  By  putting a single "addons"  key at the top  level: we
# would cause  all the compilers to  be installed for all  the builds in
# the matrix; we do not want this.

#page
#### about compiler selection
#
# We select the  compiler we want with the "compiler"  key.  This should
# set the environment variable CC to the associated compiler executable;
# I have verified that it actually does so when the language is C.  I am
# not sure that it actually does it when the language is C++.
#
# To check which C or C++ compiler  is actually selected, we can put the
# following  in  every "script:"  key,  before  running the  "configure"
# script as follows:
#
#    script: |
#      echo CC=$CC; $CC --version;
#      echo CXX=$CXX; $CXX --version;
#      ./configure
#

#page
#### about dependency packages
#
# We  install  dependency  packages under  "/tmp/mine",  so  appropriate
# directories must  be added to  the global path  environment variables,
# otherwise the installed packages will  not be found and used correctly
# by the "configure" script.
#
# Notice that (as of May 17,  2018) Travis CI's run-time system raises a
# warning if the first directory in the PATH environment variable is not
# the one  that it sets.   So, for now,  we append the  custom directory
# rather than prepend it;  this is not the best if we  want to make sure
# that the executables we install are  found before the one installed by
# the platform.
#
# We need the following in the global environment:
#
#   env:
#     global:
#       - PATH=$PATH:/tmp/mine/bin;
#       - LD_LIBRARY_PATH=/tmp/mine/lib:$LD_LIBRARY_PATH;
#       - PKG_CONFIG_PATH=/tmp/mine/lib/pkgconfig:$PKG_CONFIG_PATH;
#
# Alternatively, we can put the following in every "script:" key, before
# running the "configure" script as follows:
#
#   script: |
#     export PATH=$PATH:/tmp/mine/bin;
#     export LD_LIBRARY_PATH=/tmp/mine/lib:$LD_LIBRARY_PATH;
#     export PKG_CONFIG_PATH=/tmp/mine/lib/pkgconfig:$PKG_CONFIG_PATH;
#     ./configure
#

#page
#### global configuration

language: c

# Unbreak clang address sanitizer, needs SYS_PTRACE
# https://github.com/google/sanitizers/issues/764#issuecomment-276663297
# https://github.com/travis-ci/travis-ci/issues/9033
sudo: required

# Let's just look at the project's dashboard at Travis CI's site.
#
notifications:
  email: false

# We do no git operations, so set the "git clone" depth to the minimum.
#
git:
  depth: 1

# These branches are the interesting ones at the forked repository:
#
#   <https://github.com/marcomaggi/libexpat/>
#
branches:
  only:
    - forked.marcomaggi-2018-08-20
    - run-xmltest-review.marcomaggi-2018-08-21
    - single-makefile.marcomaggi-2018-08-20

# NOTE There must be only *one* env.global key!!!  Otherwise the earlier
# settings will be ineffective.
env:
  global:
    - MAKEFLAGS="-j 2"
    - PATH=$PATH:/tmp/mine/bin
    - LD_LIBRARY_PATH=/tmp/mine/lib:$LD_LIBRARY_PATH;
    - PKG_CONFIG_PATH=/tmp/mine/lib/pkgconfig:$PKG_CONFIG_PATH;

#page
#### build scripts

before_script:
  # On Linux the GNU Libtool  preparation script is called "libtoolize",
  # while on OS X it is called "glibtoolize".
  - if test "$TRAVIS_OS_NAME" = osx ; then export LIBTOOLIZE=glibtoolize; else true; fi
  - cd expat; sh ./autogen.sh;

matrix:
  fast_finish: true

  include:

## ------------------------------------------------------------------------
## Building with GNU Autoconf.

    # Plain build under Ubuntu GNU+Linux "trusty", GCC 5.
    - os: linux
      dist: trusty
      compiler: gcc-5
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - texinfo
            - gcc-5
            - docbook2x
            - dos2unix
      script: "cd expat; ./configure --enable-maintainer-mode; make all; make check; make run-xmltest;"

    # Plain build under Ubuntu GNU+Linux "trusty", GCC 6.
    - os: linux
      dist: trusty
      compiler: gcc-6
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - texinfo
            - gcc-6
            - docbook2x
            - dos2unix
      script: "cd expat; ./configure --enable-maintainer-mode; make all; make check; make run-xmltest;"

    # Plain build under Ubuntu GNU+Linux "trusty", GCC 7.
    - os: linux
      dist: trusty
      compiler: gcc-7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - texinfo
            - gcc-7
            - docbook2x
            - dos2unix
      script: "cd expat; ./configure --enable-maintainer-mode; make all; make check; make run-xmltest;"

    # Plain build under Ubuntu GNU+Linux "trusty", GCC 8.
    - os: linux
      dist: trusty
      compiler: gcc-8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - texinfo
            - gcc-8
            - docbook2x
            - dos2unix
      script: "cd expat; ./configure --enable-maintainer-mode; make all; make check; make run-xmltest;"

    # Plain build  under Ubuntu GNU+Linux "trusty",  CLang automatically
    # selected by Travis CI.
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - texinfo
            - docbook2x
            - dos2unix
      compiler: clang
      script: "cd expat; ./configure --enable-maintainer-mode; make all CFLAGS='-Wno-unknown-attributes'; make check CFLAGS='-Wno-unknown-attributes';"

## ------------------------------------------------------------------------
## Building under OS X.

    # Plain build under OS X, XCode 7.3, CLang automatically selected by
    # Travis CI.
    - os: osx
      osx_image: xcode7.3
      compiler: clang
      script: |
        cd expat;
        ./configure --enable-maintainer-mode --without-docbook;
        make all CFLAGS='-Wno-unknown-attributes';
        make check CFLAGS='-Wno-unknown-attributes';

    # Plain build under OS X, XCode 8.3, CLang automatically selected by
    # Travis CI.
    - os: osx
      osx_image: xcode8.3
      compiler: clang
      script: |
        cd expat;
        ./configure --enable-maintainer-mode --without-docbook;
        make all CFLAGS='-Wno-unknown-attributes';
        make check CFLAGS='-Wno-unknown-attributes';
        make run-xmltest;

## ------------------------------------------------------------------------
## Building with CMake

    # Plain build under Ubuntu GNU+Linux "trusty", GCC 8 and CMake.
    - os: linux
      dist: trusty
      compiler: gcc-8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - texinfo
            - gcc-8
            - cmake
            - docbook2x
            - dos2unix
      script: "cd expat; cmake .; make all; make test;"

## ------------------------------------------------------------------------
## Code coverage.

    # Codecov support under Ubuntu GNU+Linux "trusty", GCC 8, GNU
    # Autoconf.
    #
    # We need  "-lgcov" in LDFLAGS  because, for  some reason it  is not
    # added when linking the static library "libruntests.a".
    - os: linux
      dist: trusty
      compiler: gcc-8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - texinfo
            - gcc-8
            - cmake
            - docbook2x
            - dos2unix
      script: |
        cd expat;
        ./configure --enable-maintainer-mode CFLAGS='-O0 --coverage' CXXFLAGS='-O0 --coverage' LDFLAGS='-lgcov';
        make all;
        make check;
      after_success:
        bash <(curl -s https://codecov.io/bash) -xgcov-8

#page
#### done

### end of file
# Local Variables:
# paragraph-start: "#[ \t].+\\|$"
# paragraph-separate: "#[ \t]*$"
# fill-prefix: "# "
# page-delimiter: "^#page"
# End:
